apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingredients-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingredients
  template:
    metadata:
      labels:
        app: ingredients
    spec:
      initContainers:
        - name: run-migrations
          image: ingredients_migrations_image:latest
          imagePullPolicy: Never
          command: ['yarn', 'migrate']
          env:
            - name: DB_URL
              value: 'postgresql://demo:demo@ingredients-db:5432/demo?sslmode=disable'
      containers:
        - image: ingredients_image
          imagePullPolicy: Never
          name: ingredients-container
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: ingredients-config
            - secretRef:
                name: ingredients-secret
