replicaCount: 1

selector:
  app: client

image:
  name: client-image
  tag: 0.1
  port: 80

service:
  ports:
    - name: http
      port: 80
      containerPort: 4000

ingress:
  path: /
  port: 80
