replicaCount: 1

selector:
  app: meals

image:
  name: meals-image
  tag: 0.1
  port: 8080

service:
  ports:
    - name: http
      port: 80
      containerPort: 8080

ingress:
  path: /api/v1/meals
  port: http

migrations:
  image:
    name: meals-migrations-image
    tag: 0.1
  config:
    POSTGRESQL_URL: 'postgres://demo:demo@meals-db:5432/demo?sslmode=disable'
    VERSION: '0.1'

configs:
  POSTGRES_DB: demo
  POSTGRES_HOST: postgres

secrets:
  POSTGRES_USER: 'ZGVtbw=='
  POSTGRES_PASSWORD: 'ZGVtbw=='

postgresql:
  fullnameOverride: postgres # використовується як хост
  postgresqlDatabase: 'demo'
  postgresqlUsername: 'demo'
  postgresqlPassword: 'demo'
  persistence:
    size: 2Gi
    mountPath: /var/lib/postgresql/data
