{{- define "common.circuit-breaker" -}}

{{- $common := dict "Values" .Values.common -}} # Values з common Chart
{{- $noCommon := omit .Values "common" -}} # Values з основного Chart
{{- $overrides := dict "Values" $noCommon -}} # записуємо common Values в змінну Values
{{- $noValues := omit . "Values" -}} # містить усе крім Values, зокрема Chart, Release
{{- with merge $noValues $overrides $common -}}
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "common.fullname" . }}-destination
spec:
  host: {{ include "common.fullname" . }}
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: {{ .Values.circuitbreaker.consecutive5xxErrors }}
      interval: {{ .Values.circuitbreaker.interval }}
      baseEjectionTime: {{ .Values.circuitbreaker.baseEjectionTime }}
      maxEjectionPercent: {{ .Values.circuitbreaker.maxEjectionPercent }}
{{- end -}}
{{- end -}}
