{{- define "common.deployment" -}}

{{- $common := dict "Values" .Values.common -}} # Values з common Chart
{{- $noCommon := omit .Values "common" -}} # Values з основного Chart
{{- $overrides := dict "Values" $noCommon -}} # записуємо common Values в змінну Values
{{- $noValues := omit . "Values" -}} # містить усе крім Values, зокрема Chart, Release
{{- with merge $noValues $overrides $common -}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount   }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.migrations }}
      initContainers:
        - name: wait-for-db
          image: alpine:3.14
          command: ['sleep', '1m']
        - name: {{ .Values.migrations.image.name }}
          image: {{ .Values.migrations.image.name }}:{{ .Values.migrations.image.tag }}
          command: ['yarn', 'migrate']
          env:
            - name: DB_URL
              value: {{ .Values.migrations.config.POSTGRESQL_URL | quote }}
            - name: VERSION
              value: {{ .Values.migrations.config.VERSION | quote }}
      {{- end }}
      containers:
        - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          name: {{ .Values.image.name }}
          imagePullPolicy: Never
          ports:
            {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
            {{- end }}
          envFrom:
            - configMapRef:
                optional: true
                name: {{ include "common.fullname" . }}-config
            - secretRef:
                optional: true
                name: {{ include "common.fullname" . }}-secret
{{- end -}}
{{- end -}}
