replicaCount: 1

selector:
  app: ingredients

image:
  name: ingredients
  tag: 0.1
  port: 8080

service:
  ports:
    - name: http
      port: 80
      containerPort: 8080

ingress:
  path: /api/v1/ingredients
  port: http

migrations:
  image:
    name: ingredients_migrations_image
    tag: 0.1
  config:
    POSTGRESQL_URL: 'postgres://demo:demo@ingredients-db:5432/demo?sslmode=disable'
    VERSION: '0.1'

configs:
  POSTGRES_DB: demo
  POSTGRES_HOST: postgres

secrets:
  POSTGRES_USER: 'ZGVtbw=='
  POSTGRES_PASSWORD: 'ZGVtbw=='
