replicaCount: 1

selector:
  app: cuisines

image:
  name: cuisines-image
  tag: 0.1
  port: 3000

service:
  ports:
    - name: http
      port: 80
      containerPort: 3000

ingress:
  path: /api/v1/cuisines
  port: 80

migrations:
  image:
    name: cuisines-migrations-image
    tag: 0.1
  config:
    POSTGRESQL_URL: 'postgresql://demo:demo@cuisines-db:5432/demo?sslmode=disable'
    VERSION: '0.1'

configs:
  POSTGRES_DB: demo
  POSTGRES_HOST: postgres

secrets:
  username: 'ZGVtbw=='
  password: 'ZGVtbw=='

postgresql:
  auth:
    postgresPassword: 'demo'
    username: 'demo'
    password: 'demo'
    database: 'demo'
  fullnameOverride: cuisines-db # використовується як хост
  nameOverride: cuisines-db
  primary:
    persistence:
      size: 2Gi
      mountPath: /var/lib/postgresql/data

virtualservice:
  timeout: '5s'

circuitbreaker:
  consecutive5xxErrors: 5
  interval: '10s'
  baseEjectionTime: '30s'
  maxEjectionPercent: 80
