replicaCount: 1

selector:
  app: ingredients

image:
  name: ingredients-image
  tag: 0.1
  port: 3000

service:
  ports:
    - name: http
      port: 80
      containerPort: 3000

ingress:
  path: /api/v1/ingredients
  port: 80

migrations:
  image:
    name: ingredients-migrations-image
    tag: 0.1
  config:
    POSTGRESQL_URL: 'postgresql://demo:demo@ingredients-db:5432/demo?sslmode=disable'
    VERSION: '0.1'

configs:
  POSTGRES_DB: demo
  POSTGRES_HOST: postgres

secrets:
  username: 'ZGVtbw=='
  password: 'ZGVtbw=='

postgresql:
  auth:
    postgresPassword: 'demo'
    username: 'demo'
    password: 'demo'
    database: 'demo'
  fullnameOverride: ingredients-db # використовується як хост
  nameOverride: ingredients-db
  primary:
    persistence:
      size: 2Gi
      mountPath: /var/lib/postgresql/data
