apiVersion: apps/v1
kind: Deployment
metadata:
  name: meals-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meals
  template:
    metadata:
      labels:
        app: meals
    spec:
      initContainers:
        - name: run-migrations
          image: meals_migrations_image:latest
          imagePullPolicy: Never
          command: ['yarn', 'migrate']
          env:
            - name: DB_URL
              value: 'postgresql://demo:demo@meals-db:5432/demo?sslmode=disable'
      containers:
        - image: meals_image
          imagePullPolicy: Never
          name: meals-container
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: meals-config
            - secretRef:
                name: meals-secret
