apiVersion: apps/v1
kind: Deployment
metadata:
  name: cuisines-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cuisines
  template:
    metadata:
      labels:
        app: cuisines
    spec:
      initContainers:
        - name: run-migrations
          image: cuisines_migrations_image:latest
          imagePullPolicy: Never
          command: ['yarn', 'migrate']
          env:
            - name: DB_URL
              value: 'postgresql://demo:demo@cuisines-db:5432/demo?sslmode=disable'
      containers:
        - image: cuisines_image
          imagePullPolicy: Never
          name: cuisines-container
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: cuisines-config
            - secretRef:
                name: cuisines-secret
